apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: expense-tracker
  template:
    metadata:
      labels:
        app: expense-tracker
    spec:
      containers:
      - name: expense-tracker
        image: <registry-name>.azurecr.io/expense-tracker:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        volumeMounts:
        - name: expense-data
          mountPath: /app
      volumes:
      - name: expense-data
        persistentVolumeClaim:
          claimName: expense-pvc