apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: weather-app
  template:
    metadata:
      labels:
        app: weather-app
    spec:
      containers:
      - name: weather-app
        image: <registry-name>.azurecr.io/weather-app:v1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_ENV
          value: "production"
        - name: OPENWEATHER_API_KEY
          valueFrom:
            secretKeyRef:
              name: weather-api-secret
              key: api-key