---
- name: Deploy Expense Tracker to Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Apply Kubernetes PVC
      kubernetes.core.k8s:
        src: ../pvc.yaml
        state: present

    - name: Apply Kubernetes deployment
      kubernetes.core.k8s:
        src: ../deployment.yaml
        state: present

    - name: Apply Kubernetes service
      kubernetes.core.k8s:
        src: ../service.yaml
        state: present